# To use:
#   $ conda env create -f environment.yml
#   $ conda activate <name>
name: machinelearnear-default
dependencies:
  - python=3.9
  - pip
  - nb_conda_kernels
  - ipykernel
  - ipywidgets
  - gh
  - opencv
  - ffmpeg
  - pip:
    - torch>=1.7.1
    - torchvision
    - numpy
    - scipy